services:
  app:
    build: .
    container_name: flask_app
    ports:
      - 8000:8000
    networks:
      - flask-network

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - 80:80
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - flask-network

networks:
  flask-network:
    driver: bridge

